Стилизация главной страницы
htmlacademy-htmlcss/674831-sedona-31 pull request #5
Opened 2021-05-31 07:49 UTC by Olyash28

2021-06-01 08:40 UTC, ValeryKrukovich requested changes

2021-06-01 08:40 UTC, ValeryKrukovich commented on css/style.css
> +  font-family: "PT Sans", "Arial", sans-serif;
Arial не обязательно брать в кавычки, в них берутся названия составные (например из нескольких слов)

2021-06-01 08:40 UTC, ValeryKrukovich commented on css/style.css
> +/*преимущества*/
учись избегать кириллицы при работе.
только латиница! это почти закон)

2021-06-01 08:40 UTC, ValeryKrukovich commented on css/style.css
> +.hostel-search-form {
не оставляй пустые правило в коде

2021-06-01 08:40 UTC, ValeryKrukovich commented on css/style.css
> +
лишние пустые строки в конце файла - не есть хорошо

2021-06-01 08:40 UTC, ValeryKrukovich commented on css/style.css
> +h2, h3 {
К этому у проверяющего наставника могут возникнуть вопросы, будь готова аргументировать свою позицию в этом

2021-06-01 08:40 UTC, ValeryKrukovich commented on index.html
> +      <section class="main-bg">
А если тут сделать все одной svg?
И подумай нужен ли тут семантический тег section.

2021-06-01 08:40 UTC, ValeryKrukovich commented on index.html
>        <h2 hidden>Остальные пять причин</h2>
Меня смущает что у тебя заголовок сам по себе, а например нижняя контентная секция без заголовка вообще.
Подумай что описывает этот заголовок и к какому контенту он относится?

2021-06-01 08:40 UTC, ValeryKrukovich commented on index.html
> +    <section>
Не совсем правильно оборачивать одно изображение в секции, это семантический тег со своей смысловой нагрузкой.
Есть нужна обертка ради стилизации - делай div.

2021-06-02 11:39 UTC, Olyash28 commented on css/style.css
> +  font-family: "PT Sans", "Arial", sans-serif;
Поняла

2021-06-02 11:39 UTC, Olyash28 commented on css/style.css
> +/*преимущества*/
исправлю

2021-06-02 11:40 UTC, Olyash28 commented on css/style.css
> +.hostel-search-form {
страюсь не оставлять)

2021-06-02 11:42 UTC, Olyash28 commented on css/style.css
> +
убрала

2021-06-02 11:43 UTC, Olyash28 commented on css/style.css
> +h2, h3 {
у меня тоже к этому вопросы) уберу

2021-06-02 11:45 UTC, Olyash28 commented on index.html
> +      <section class="main-bg">
одной svg проще, действительно

2021-06-02 11:46 UTC, Olyash28 commented on index.html
>        <h2 hidden>Остальные пять причин</h2>
с секциями разобралась

2021-06-02 11:48 UTC, Olyash28 commented on index.html
> +    <section>
в footer дивы сделаю, согласна

2021-06-03 07:12 UTC, ValeryKrukovich approved these changes

2021-06-03 07:12 UTC, merged